title: LeCo Ultimate Study Plan
description: A comprehensive 8-week study plan for technical interviews
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true 